project:
  type: website
  output-dir: docs

website:
  title: "Tech blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JCfly3000


  page-footer:
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/)."


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css


