project:
  type: website
  output-dir: docs

website:
  title: "Tech blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JCfly3000


  page-footer:
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/)."



format:
  html:
    toc: true
    toc-title: 'On this page'
    toc-location: right
    code-fold: show
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-copy: true
    
    theme:
      - cosmo
      - brand
    css: styles.css


filters:
  - foldableCodeBlcok.lua