---
title: "Project"

---


# [SQL Handbook](https://jcfly3000.github.io/into_sql/)

This document provides a comprehensive guide to performing common data manipulation tasks using SQL, R, and Python. It serves as a reference for understanding how to achieve similar outcomes across these three popular data analysis tools.


# [R Handboook](https://jcfly3000.github.io/Into-R/)

This project is a comprehensive guide to the R programming language, built with Quarto. It covers a wide range of topics, from the fundamentals of R to advanced applications in data manipulation, visualization, and publishing.

# [Python Handbook](https://jcfly3000.github.io/Into-Python/)

a comprehensive guide to Python for data science, covering a range of topics from the fundamentals to more advanced applications.

# [Stat Handbook](https://jcfly3000.github.io/into_stat/)

This collection of documents serves as a practical guide and a series of case studies in statistical analysis and machine learning. Each section explores a different dataset and a different set of techniques, providing a hands-on approach to learning and applying these methods.



# [AI Handbook](https://jcfly3000.github.io/into_AI/)

a comprehensive resource for developers and data scientists looking to harness the power of Artificial Intelligence. This Quarto-based website provides a curated collection of tutorials, guides, and practical examples for using a variety of AI tools and models in both R and Python.


